server:
  port: 8050
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qin453633639/springcloud-config/     # 配置git仓库的地址
          search-paths: config                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: qin453633639                                            # git仓库的账号
          password: QinWei19910324
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/