server:
  port: 8001
spring:
  application:
    name: microservice-provider-user    # 项目名称尽量用小写
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true

master:
  datasource:
    url: jdbc:mysql://192.168.20.10:3306/my
    username: root
    password: qinwei
    driverClassName: com.mysql.jdbc.Driver
